
#ifndef __SYMBOID_ASTRO_UICONTROLS_QT_DEFS_H__
#define __SYMBOID_ASTRO_UICONTROLS_QT_DEFS_H__

#include "sdk/defs.h"

#ifdef BUILD_ASTRO_UICONTROLS_QT
    #define ASTRO_UICONTROLS_QT_API SY_API_EXPORT
#else
    #define ASTRO_UICONTROLS_QT_API SY_API_IMPORT
#endif

#endif // __SYMBOID_ASTRO_UICONTROLS_QT_DEFS_H__
